### PR TITLE
Add z3 (leo) device.

### PR DESCRIPTION
**Pull request by nailyk-fr**
Add leo device into local_manifests.

### CODE REVIEW

**Comment by AdFad666** [comment]
Do not use z3 the device codename is leo

**Comment by nailyk-fr** [comment]
I'm confused. CM always used z3 for this device codename as HD2 is also named leo. I will keep resilient with CM sources and ask for this a few hours ago...

**Comment by AdFad666** [comment]
CM used z3 and it was the wrong decision. It is (one of many) reasons why official CM on Sony devices died. I refuse to allow the z3 nonsense from CM into these repos. I just saw it was already added to shinano and I will revert it shortly.

Please keep leo, I will accept only minimal changes for easy merge/rebase.

**Comment by nailyk-fr** [comment]
> Please keep leo, I will accept only minimal changes for easy merge/rebase. 

Are you talking about SonyCM repo or CM gerrit? 
I don't think two device with the same codename into CyanogenMod can work that is why I renamed it, after the hangouts discuss. 
Isn't the purpose of SonyCM? Prepare devices tree before gerrit PR? 

Thanks.

**Comment by AdFad666** [comment]
I'm afraid that is not the purpose of this GitHub Org. Unfortunately Sony devices will not get back into CM for a very long time due to missing critical pieces of proprietary software. Sony has an "OSS or GTFO" attitude so the blobs provided are the very minimum to get a device booting.

This is simply a place to make unofficial builds with the few parts we are given.

FYI some of the parts missing include: audio calibration, VoLTE, GPS, DRM. There are more but those are the biggest killers of CM support.

**Comment by nailyk-fr** [comment]
> I'm afraid that is not the purpose of this GitHub Org

Sure sorry. But I will not use gerrit to contact you (even if you have +2 ;) ) and don't know other ways to do. (my nick is nailyk on IRC and xda)
Working together is the only way of improvement, so I will made the new PR your request asap for this purpose. Anyway I think a solution need to be found. 

Sorry for annoyance.

**Comment by AdFad666** [comment]
Nothing to apologize for, I am very happy to work together here, but I also want it to be clear that Sony on CM (or any other custom ROM project) is unrealistic with what is available to us.

It's only to prevent any disappointment in the future.

Of course we can boot and run apps very well, but due to missing functionality we cannot be official.

**Pull request closed without merging**
